/**
 * Markdown → HTML, the step between the serialiser and the PDF (`M-13`).
 *
 * ⚠️ THIS ADDS NO SUBSTANCE. `src/export/markdown.ts` is the single source of
 * what an exported document *says*; this module decides only how it looks on a
 * printed page. Every heading, table, label and disclaimer in the output came
 * from the Markdown, so the PDF cannot state anything the Markdown does not —
 * there is no second content model to drift.
 *
 * That is the whole reason the pipeline is Markdown → HTML → PDF rather than
 * two renderers over `AnalysisView`. A second renderer would be a second
 * opinion about provenance, confidence and artifact states, and the two would
 * disagree the first time one was changed alone.
 *
 * MERMAID FENCES SURVIVE AS RENDER TARGETS. A ```mermaid block becomes
 * `<pre class="mermaid">` holding the original source, which is what the
 * browser's Mermaid runtime looks for. `FR-050` wants the diagram rendered in
 * the PDF and the source present in the Markdown; both come from the same
 * fence.
 *
 * THE STYLESHEET IS PRINT-FIRST. Page breaks are avoided inside tables and
 * diagrams, because a risk register split across a page boundary loses its
 * header row and a diagram split in half is worse than one on its own page.
 */

import { marked } from "marked";

/**
 * `FR-051` forbids marketing content, and this file is where a footer, logo or
 * "generated by" line would most naturally be added by someone tidying up the
 * page. There is none, and there should be none: the only footer is the page
 * number, which is print furniture rather than content.
 */
const STYLES = `
  :root { color-scheme: light; }
  body {
    font-family: "Liberation Sans", "Segoe UI", -apple-system, system-ui, "Helvetica Neue", Arial, sans-serif;
    font-size: 10.5pt;
    line-height: 1.5;
    color: #17202a;
    margin: 0;
  }
  h1 { font-size: 20pt; margin: 0 0 4pt; letter-spacing: -0.01em; }
  h2 {
    font-size: 13pt;
    margin: 20pt 0 6pt;
    padding-bottom: 3pt;
    border-bottom: 1px solid #d5dbe1;
    /* A section heading stranded at the foot of a page reads as a missing
       section on the page that follows it. */
    break-after: avoid;
    break-inside: avoid;
  }
  h3 { font-size: 11.5pt; margin: 14pt 0 4pt; break-after: avoid; }
  h4 { font-size: 10.5pt; margin: 12pt 0 4pt; color: #33414f; break-after: avoid; }
  p { margin: 0 0 7pt; }
  ul, ol { margin: 0 0 7pt; padding-left: 18pt; }
  li { margin-bottom: 3pt; }
  code {
    font-family: "Liberation Mono", "Cascadia Mono", Consolas, "SF Mono", Menlo, monospace;
    font-size: 9pt;
    background: #f2f4f6;
    padding: 1pt 3pt;
    border-radius: 3px;
  }
  strong { font-weight: 600; }
  em { color: #48545f; }

  /* The metadata block and every data table. */
  table {
    border-collapse: collapse;
    width: 100%;
    margin: 0 0 10pt;
    font-size: 9pt;
    break-inside: avoid;
  }
  th, td {
    border: 1px solid #d5dbe1;
    padding: 4pt 6pt;
    text-align: left;
    vertical-align: top;
  }
  th { background: #f2f4f6; font-weight: 600; }

  /* Degradation and low-confidence notices. They lead the document for a
     reason; they must not read as decoration. */
  blockquote {
    margin: 0 0 10pt;
    padding: 7pt 10pt;
    background: #fdf6e6;
    border-left: 3px solid #d9a441;
    break-inside: avoid;
  }
  blockquote p:last-child { margin-bottom: 0; }

  hr { border: 0; border-top: 1px solid #d5dbe1; margin: 16pt 0; }

  /* A diagram split across a page boundary is worse than one on its own. */
  pre.mermaid {
    break-inside: avoid;
    margin: 10pt 0;
    text-align: center;
    /* Hidden until Mermaid replaces it: the raw source flashing into the PDF
       would be the diagram failing to render, printed. */
    font-size: 0;
  }
  pre.mermaid svg { max-width: 100%; height: auto; font-size: 10pt; }

  /* Mermaid could not parse the source. FR-050 puts the source in the
     Markdown export; showing it here too is better than an empty space that
     looks like a diagram nobody drew. */
  pre.mermaid-failed {
    font-family: "Liberation Mono", "Cascadia Mono", Consolas, monospace;
    font-size: 8.5pt;
    background: #f2f4f6;
    border: 1px solid #d5dbe1;
    padding: 8pt;
    white-space: pre-wrap;
    text-align: left;
    break-inside: avoid;
  }
`;

/**
 * Escapes text for placement inside an HTML element.
 *
 * Applied to Mermaid source specifically. Diagram labels are free text taken
 * from a user's own document, and a `<` in a component name would otherwise
 * open a tag inside the page.
 */
const escapeHtml = (text: string): string =>
  text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");

/**
 * Renders the exported Markdown as a complete HTML document.
 *
 * Pure and offline. Nothing is fetched: the stylesheet is inline, no font is
 * requested from a network, and the Mermaid runtime is injected by the PDF
 * step from disk rather than from a CDN. An export must not depend on an
 * external service being reachable.
 */
export function renderExportHtml(markdown: string, title: string): string {
  const renderer = new marked.Renderer();

  // ⚠️ RAW HTML IS ESCAPED, NEVER EMITTED (`NFR-027`, `NFR-024`).
  //
  // `marked` passes HTML in its source through untouched — that is Markdown's
  // specified behaviour and it is the wrong behaviour here. This document is
  // built from **artifact content**, which is model output derived from the
  // user's own submitted text, so a `<script>` reaching this function is a
  // reachable path and not a hypothetical one: an input that induces markup in
  // an artifact, then an export to PDF, and it executes.
  //
  // The rendering context makes that worse rather than academic. `export/pdf`
  // launches Chromium with `--no-sandbox` (required to run as root in a
  // container), so script execution there is unsandboxed script execution.
  //
  // Escaped rather than stripped: a user who wrote `<thing>` in their input
  // should see `<thing>` in their document, not a silent deletion.
  renderer.html = ({ text }): string => escapeHtml(text);

  // The renderer above closes **block** HTML. Inline HTML — an `<img>` in the
  // middle of a paragraph — is produced by a separate tokenizer and would
  // otherwise still pass through, which is exactly how the `onerror` case
  // survives a fix that only overrides the renderer. Refusing the match makes
  // the tag ordinary text, and ordinary text is escaped on the way out.
  const tokenizer = new marked.Tokenizer();
  tokenizer.tag = () => undefined;

  // ⚠️ ONLY INERT URL SCHEMES SURVIVE (`NFR-027`).
  //
  // Escaping tags does not close a link: `[text](javascript:...)` is ordinary
  // Markdown, and artifact content is interpolated into this document as
  // Markdown, so a project name or a mitigation containing link syntax becomes
  // a real anchor. `javascript:` and `data:` are the two that execute.
  //
  // A refused scheme keeps its text and loses its href, so the reader still
  // sees what was written and cannot be navigated by it.
  const SAFE_SCHEME = /^(https?:|mailto:|#|\/|\.)/i;
  renderer.link = ({ href, text }): string =>
    SAFE_SCHEME.test(href)
      ? `<a href="${escapeHtml(href)}">${text}</a>`
      : `${text} (link removed: unsupported scheme)`;

  // Fenced `mermaid` becomes a render target rather than a code block; every
  // other fence stays a code block.
  renderer.code = ({ text, lang }): string =>
    lang === "mermaid"
      ? `<pre class="mermaid">${escapeHtml(text)}</pre>`
      : `<pre><code>${escapeHtml(text)}</code></pre>`;

  const body = marked.parse(markdown, {
    renderer,
    tokenizer,
    // GitHub-flavoured tables are what the serialiser emits; without this the
    // risk register and artifact status arrive as unreadable pipe-delimited
    // paragraphs.
    gfm: true,
    async: false,
  });

  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><title>${escapeHtml(title)}</title>
<style>${STYLES}</style></head>
<body>${body}</body></html>`;
}
