/**
 * Reviewer packet generation for the `M-08` partial rubric review.
 *
 *   npm run review:packets          write packets to research/reviews/
 *   npm run review:packets -- --check   verify the written packets are current
 *
 * Reads the golden corpus and the committed recordings; writes Markdown. No
 * provider, no database, no network, no cost.
 *
 * SOURCE RECORDINGS ARE NEVER WRITTEN. They are the evidence, and evidence a
 * tool can edit is not evidence. Every recording is read through the manifest-
 * verifying store, so a hand-edited one is refused rather than packaged
 * (`RecordingIntegrityError`).
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { loadCorpus } from "../src/regression/corpus.js";
import {
  createRecordingStore,
  type CaseRecording,
} from "../src/regression/recording-store.js";
import {
  buildIndex,
  buildPackets,
  buildUnblindingIndex,
  type PacketInput,
} from "../src/regression/review-packet.js";

const CORPUS_VERSION = "corpus-v1";

const OUTPUT_ROOT = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "../../research/reviews",
);
const OUTPUT_DIR = path.join(OUTPUT_ROOT, `m08-partial-${CORPUS_VERSION}`);
const UNBLINDING_FILE = "UNBLINDING-INDEX.do-not-open-before-review.json";

const README = `# M-08 partial rubric review — ${CORPUS_VERSION}

Generated by \`npm run review:packets\`. Do not edit the packets by hand before
reviewing; regenerate instead.

**What this is.** One packet per committed recording, carrying the submitted
input, the stage outputs that were captured, and the \`docs/10\` §4.4 record to
fill in.

**What it is not.** Not an M-08 pass, and not capable of becoming one. \`docs/10\`
§3.5 requires all seven criteria to pass per analysis; C-3 and C-6 have no
material in these recordings and are marked not assessable. §4.1 requires ≥20
analyses per input type, which this set does not reach.

**Corpus, not runtime.** The recordings were captured 2026-08-14. Per
\`docs/12\` D-24 they are not evidence that the prompts now in force produce
these responses.

**Reviewer independence.** \`docs/10\` §4.3 excludes AI review in any capacity,
for any criterion. Every verdict in these packets must be written by a human. If
the reviewer is also the author of the analysis, the result is recorded as
single-reviewer and cannot satisfy an agreement measurement. A reviewer who did
not build this system is what §8 ambiguity A-1 has been waiting for — and if two
people review the same packets, §5 agreement measurement becomes available.

**How to review.** Read \`INDEX.md\` for what exists and which criteria each
packet can support. Then, per packet: read the input, read the stage outputs,
and record a verdict **and** evidence for C-1, C-2, C-4, C-5 and C-7. §3.3 is
strict — a verdict without evidence is not recorded as a verdict. C-3 and C-6
arrive marked not assessable; leave them. Judge only what is in front of you.

**Do not open \`${UNBLINDING_FILE}\` until the verdicts are written.** It carries
the fragment version and model identity that §4.2 keeps out of the packets.
`;

const inputs = (): {
  packets: readonly PacketInput[];
  recordings: Map<string, CaseRecording>;
} => {
  const store = createRecordingStore();
  const recorded = new Set(store.list(CORPUS_VERSION));
  const recordings = new Map<string, CaseRecording>();
  const packets: PacketInput[] = [];

  for (const corpusCase of loadCorpus()) {
    if (!recorded.has(corpusCase.caseId)) continue;
    const verified = store.read(CORPUS_VERSION, corpusCase.caseId);
    if (verified === undefined) continue;
    recordings.set(corpusCase.caseId, verified.recording);
    packets.push({ corpusCase, recording: verified.recording });
  }

  return { packets, recordings };
};

const files = (): {
  out: Map<string, string>;
  packetCount: number;
} => {
  const { packets: packetInputs, recordings } = inputs();
  const packets = buildPackets(packetInputs);
  const out = new Map<string, string>();

  const stagesByCase = new Map<string, readonly string[]>(
    [...recordings].map(([caseId, recording]) => [
      caseId,
      recording.stages.map((stage) => stage.stageKey),
    ]),
  );

  out.set("README.md", README);
  out.set("INDEX.md", buildIndex(packets, stagesByCase));
  for (const packet of packets) out.set(packet.filename, packet.content);
  out.set(UNBLINDING_FILE, buildUnblindingIndex(packets, recordings));
  return { out, packetCount: packets.length };
};

const check = process.argv.includes("--check");
const { out: written, packetCount } = files();

if (packetCount === 0) {
  console.error(
    "No recordings matched a corpus case. Nothing to package — check " +
      "research/regression-recordings/ and the corpus manifest.",
  );
  process.exit(1);
}

if (check) {
  const problems: string[] = [];
  for (const [name, content] of written) {
    const file = path.join(OUTPUT_DIR, name);
    if (!fs.existsSync(file)) {
      problems.push(`${name} is missing`);
      continue;
    }
    if (fs.readFileSync(file, "utf8") !== content) {
      problems.push(`${name} differs from what the sources produce`);
    }
  }

  if (problems.length === 0) {
    console.log(`✅ ${String(packetCount)} packet(s) present and current.`);
    process.exit(0);
  }
  console.error("❌ Review packets are stale:");
  for (const problem of problems) console.error(`   ${problem}`);
  console.error("\nRun `npm run review:packets` to regenerate.");
  process.exit(1);
}

fs.mkdirSync(OUTPUT_DIR, { recursive: true });
for (const [name, content] of written) {
  fs.writeFileSync(path.join(OUTPUT_DIR, name), content, "utf8");
}

console.log(
  `✅ ${String(packetCount)} packet(s) written to ${path.relative(process.cwd(), OUTPUT_DIR)}`,
);
console.log("   No verdict was generated. Every verdict is yours to write.");
