/**
 * Unit — Markdown → HTML, the step between the serialiser and the PDF.
 *
 * THE PROPERTY UNDER TEST IS THAT THIS STEP ADDS NOTHING. The PDF must not be
 * able to say anything the Markdown does not, which is why the pipeline is
 * Markdown → HTML → PDF rather than two renderers over `AnalysisView`. These
 * tests pin the substance through the transformation, and pin the two things
 * that would break the PDF specifically: Mermaid fences must survive as render
 * targets, and tables must become real tables rather than pipe soup.
 */

import { test } from "node:test";
import assert from "node:assert/strict";

import { renderExportHtml } from "../../src/export/html.js";

test("a mermaid fence becomes a render target the browser will find", () => {
  const html = renderExportHtml(
    '```mermaid\nflowchart TD\n  n0["Form Watcher"]\n```\n',
    "t",
  );
  // `pre.mermaid` is exactly what `export/pdf.ts` runs Mermaid against. A
  // plain <code> block here would print the source instead of the diagram.
  assert.match(html, /<pre class="mermaid">/);
  assert.match(html, /flowchart TD/);
  assert.match(html, /Form Watcher/);
});

test("a non-mermaid fence stays a code block", () => {
  const html = renderExportHtml("```\nplain text\n```\n", "t");
  assert.match(html, /<pre><code>/);
  assert.equal(html.includes('class="mermaid"'), false);
});

test("GFM tables become real tables", () => {
  // Without `gfm`, the risk register and artifact status arrive as unreadable
  // pipe-delimited paragraphs — the two places the export carries its most
  // load-bearing states.
  const html = renderExportHtml(
    "| Artifact | Outcome |\n|---|---|\n| Risk Assessment | Omitted |\n",
    "t",
  );
  assert.match(html, /<table>/);
  assert.match(html, /<th>Artifact<\/th>/);
  assert.match(html, /<td>Omitted<\/td>/);
});

test("a blockquote survives, because degradation notices are blockquotes", () => {
  const html = renderExportHtml(
    "> **This analysis timed out.** It was stopped before finishing.\n",
    "t",
  );
  assert.match(html, /<blockquote>/);
  assert.match(html, /This analysis timed out/);
});

test("markup inside a diagram label is inert", () => {
  // Component names are the user's own text, and the diagram is rendered from
  // them. A `<` that opened a tag would put user text into the document
  // structure rather than into a label.
  const html = renderExportHtml(
    '```mermaid\nflowchart TD\n  n0["<img src=x onerror=alert(1)>"]\n```\n',
    "t",
  );
  assert.equal(html.includes("<img src=x"), false);
  assert.match(html, /&lt;img src=x/);
});

test("the title is escaped into the document head", () => {
  const html = renderExportHtml("body\n", 'A "quoted" <title>');
  assert.match(html, /<title>A &quot;quoted&quot; &lt;title&gt;<\/title>/);
});

test("the document is self-contained — nothing is fetched", () => {
  // An export that depended on a CDN would fail in exactly the environment
  // where it matters. The stylesheet is inline and no font is requested.
  const html = renderExportHtml("# Heading\n\nBody text.\n", "t");
  assert.equal(/<link[^>]+href=/.test(html), false);
  assert.equal(/<script[^>]+src=/.test(html), false);
  assert.equal(html.includes("http://"), false);
  assert.equal(html.includes("https://"), false);
});

test("FR-051 — the stylesheet introduces no marketing content", () => {
  // This module is where a footer, logo or "generated by" line would most
  // naturally be added by someone tidying up the page.
  const html = renderExportHtml("# Heading\n", "t").toLowerCase();
  for (const phrase of ["naigx", "powered by", "generated by", "learn more"]) {
    assert.equal(html.includes(phrase), false, `present: ${phrase}`);
  }
});

test("the exported substance passes through unaltered", () => {
  const markdown = [
    "# Automation Engineer",
    "",
    "**Confidence: not available.** Printing one would be inventing the measurement.",
    "",
    "*This objective was inferred — inferred from the input rather than written in it.*",
    "",
    "| Artifact | Outcome | Why |",
    "|---|---|---|",
    "| Risk Assessment | Failed | Generation was attempted and did not succeed. |",
    "",
  ].join("\n");

  const html = renderExportHtml(markdown, "Automation Engineer");

  assert.match(html, /Confidence: not available/);
  assert.match(html, /was inferred/);
  assert.match(html, /Failed/);
  assert.match(html, /Generation was attempted and did not succeed/);
});
