/**
 * Unit — the n8n workflow scaffold (D-71).
 *
 * What is pinned: the file is n8n's shape and validates against the
 * published schema; every step becomes a node with a note beside it; the
 * wiring follows step order and never feeds a trigger; an unknown node name
 * becomes a placeholder that says so rather than a silent guess; the plan
 * entry is a decision (planned or omitted with a reason); rendering is
 * deterministic.
 */

import assert from "node:assert/strict";
import { test } from "node:test";

import type {
  PortfolioProject,
  PortfolioSuggestions,
} from "../../src/nie/contracts.js";
import { validateArtifact } from "../../src/nie/artifact-validation.js";
import {
  n8nProjectOf,
  planN8nWorkflow,
  renderN8nWorkflow,
} from "../../src/nie/stages/n8n-workflow.js";

const project: PortfolioProject = {
  rank: 1,
  name: "Lead intake to CRM",
  complexity: "intermediate",
  primaryGaps: ["req-1"],
  secondaryCapabilities: ["logging"],
  whyThisProject: "It exercises the platforms the posting names.",
  businessProblem: "Leads arrive by form and are re-keyed by hand.",
  whatToBuild: "A form-triggered pipeline that qualifies and syncs leads.",
  workflow: [
    "Trigger: form submission",
    "Normalise the payload",
    "Look up the contact",
    "Branch on match",
    "Create or update the record",
    "Reverse sync on a schedule",
    "Alert on failure",
  ],
  platforms: ["n8n", "HubSpot"],
  technicalConcepts: ["webhooks"],
  evidenceToProduce: [{ type: "workflow", whatItShows: "the export" }],
  whyNotConsolidated: "only one gap",
  reusability: { provenance: "inferred", basis: "b", claim: "c" },
  estimatedEffort: "days",
  portfolioValue: "value",
  implementation: {
    platform: "n8n",
    steps: [
      {
        step: 1,
        node: "Webhook",
        purpose: "Receive the form",
        setup: ["HTTP method: POST"],
        credential: null,
      },
      {
        step: 2,
        node: "Code",
        purpose: "Normalise fields",
        setup: ["Mode: run once for all items"],
        credential: null,
      },
      {
        step: 3,
        node: "HubSpot",
        purpose: "Search contacts",
        setup: ["Resource: Contact", "Operation: Search"],
        credential: "HubSpot OAuth2 API",
      },
      {
        step: 4,
        node: "IF",
        purpose: "Matched or not",
        setup: ["Condition: contact id exists"],
        credential: null,
      },
      {
        step: 5,
        node: "HubSpot",
        purpose: "Upsert",
        setup: ["Operation: Create/Update"],
        credential: "HubSpot OAuth2 API",
      },
      {
        step: 6,
        node: "Schedule Trigger",
        purpose: "Run the reverse leg",
        setup: ["Every 15 minutes"],
        credential: null,
      },
      {
        step: 7,
        node: "Marketo Alerts",
        purpose: "Notify",
        setup: ["Send to the ops channel"],
        credential: "Marketo API",
      },
    ],
    notes: ["Attach an Error Workflow", "Test with pinned data first"],
  },
};

const portfolio: PortfolioSuggestions = {
  projects: [project],
  consolidationRationale: "one",
};

test("D-71 — renders n8n's own shape and validates against the published schema", () => {
  const doc = renderN8nWorkflow(project);
  validateArtifact("n8n_workflow", doc);
  assert.equal(doc["name"], "NAIGX scaffold — Lead intake to CRM");
  const naigx = doc["naigx"] as Record<string, unknown>;
  assert.equal(naigx["standing"], "scaffold");
  assert.equal(naigx["steps_mapped"], 6);
  assert.deepEqual(naigx["steps_unmapped"], ["Marketo Alerts"]);
});

test("D-71 — one node per step with a note beside it, plus the README and the wiring notes", () => {
  const nodes = renderN8nWorkflow(project)["nodes"] as {
    name: string;
    type: string;
    parameters: Record<string, unknown>;
  }[];
  const stepNodes = nodes.filter((n) => n.type !== "n8n-nodes-base.stickyNote");
  const notes = nodes.filter((n) => n.type === "n8n-nodes-base.stickyNote");
  assert.equal(stepNodes.length, 7);
  assert.equal(notes.filter((n) => n.name.startsWith("Note — step")).length, 7);
  assert.ok(notes.some((n) => n.name.startsWith("README")));
  assert.ok(notes.some((n) => n.name === "Wiring notes"));
  // The README states the standing, in the file, first.
  assert.match(
    String(notes[0]?.parameters["content"]),
    /scaffold generated by NAIGX, not a finished workflow/,
  );
  // Types come from the map; the same name twice stays unique for n8n.
  assert.equal(stepNodes[0]?.type, "n8n-nodes-base.webhook");
  assert.equal(stepNodes[2]?.name, "HubSpot");
  assert.equal(stepNodes[4]?.name, "HubSpot 2");
  assert.equal(stepNodes[4]?.type, "n8n-nodes-base.hubspot");
  // A step note carries purpose, setup and credential verbatim.
  const third = notes.find((n) => n.name === "Note — step 3");
  assert.match(String(third?.parameters["content"]), /Search contacts/);
  assert.match(String(third?.parameters["content"]), /- Operation: Search/);
  assert.match(
    String(third?.parameters["content"]),
    /Credential:\*\* HubSpot OAuth2 API/,
  );
});

test("D-71 — wiring follows step order and never feeds a trigger", () => {
  const connections = renderN8nWorkflow(project)["connections"] as Record<
    string,
    { main: { node: string }[][] }
  >;
  assert.equal(connections["Webhook"]?.main[0]?.[0]?.node, "Code");
  assert.equal(connections["Code"]?.main[0]?.[0]?.node, "HubSpot");
  assert.equal(connections["IF"]?.main[0]?.[0]?.node, "HubSpot 2");
  // Step 6 is a trigger: nothing feeds it, and it starts the next chain.
  assert.equal(connections["HubSpot 2"], undefined);
  assert.equal(
    connections["Schedule Trigger"]?.main[0]?.[0]?.node,
    "Marketo Alerts (replace me)",
  );
});

test("D-71 — an unknown node name becomes a placeholder that says so, never a guess", () => {
  const nodes = renderN8nWorkflow(project)["nodes"] as {
    name: string;
    type: string;
    parameters: Record<string, unknown>;
  }[];
  const placeholder = nodes.find(
    (n) => n.name === "Marketo Alerts (replace me)",
  );
  assert.equal(placeholder?.type, "n8n-nodes-base.noOp");
  const note = nodes.find((n) => n.name === "Note — step 7");
  assert.match(
    String(note?.parameters["content"]),
    /could not map "Marketo Alerts"/,
  );
});

test("D-71 — the plan is a decision: planned on n8n, omitted with the reason otherwise", () => {
  assert.equal(planN8nWorkflow(portfolio)[0]?.planned, true);
  assert.equal(n8nProjectOf(portfolio)?.name, project.name);

  const { implementation: _drop, ...bare } = project;
  const none = planN8nWorkflow({ ...portfolio, projects: [bare] })[0];
  assert.equal(none?.planned, false);
  assert.match(
    none?.omissionReason ?? "",
    /no automation-platform implementation plan/,
  );

  const make = planN8nWorkflow({
    ...portfolio,
    projects: [
      {
        ...project,
        implementation: { ...project.implementation!, platform: "Make" },
      },
    ],
  })[0];
  assert.equal(make?.planned, false);
  assert.match(make?.omissionReason ?? "", /planned on Make, not n8n/);

  assert.equal(planN8nWorkflow(undefined)[0]?.planned, false);
});

test("D-71 — rendering is deterministic", () => {
  assert.deepEqual(renderN8nWorkflow(project), renderN8nWorkflow(project));
});
